title: gali gurevich | portfolio
email: galiagurevich@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
 a showcase of my some of my dev skills
baseurl: "/jekyll-site3"
url: "https://galia1902.github.io"
twitter_username: jekyllrb
github_username:  galia1902

# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
